language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test cobertura:cobertura coveralls:report -P it-cobertura
